# Generated by Django 4.2.3 on 2023-08-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_alter_memo_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
